### ISSUE TITLE
Broken Links everywhere

### ISSUE THREAD

**Issue by ackr-8** [osc-vitap/OSC-Web#40]
Why was this even pushed to production *sigh*

**Comment by Bharath1910** [comment]
Broken links

1. Discord server link in the hero section, link it to our discord server url (https://discord.com/invite/DXgfsxXv6c)
![image](https://github.com/osc-vitap/OSC-Web/assets/72338995/7816d662-7f73-4ca0-9413-e84f09d90dd0)


2. The `contact` button in the footer is hardcoded with localhost, change it to relative route
![image](https://github.com/osc-vitap/OSC-Web/assets/72338995/350c715b-8414-4305-a0aa-d0004ad98723)

3. Event links below the hero section, I will update the links once I get them
  3.1. TechEden: https://techeden.oscvitap.org/
  3.2. IdeaOryx: NA
  3.3. Bootcamps: NA
  3.4. Cyber Syndicate: NA
  3.5. Gitty Up: NA
  3.6. SFF: NA
![image](https://github.com/osc-vitap/OSC-Web/assets/72338995/111ff33f-532c-4dd1-a629-88b8e24c9e05)
